### ISSUE TITLE
Tests failing because they refer to a file not created by sample data of the database

### ISSUE THREAD

**Issue by Vino98** [aau-giraf/web-api#123] opened 2020-04-29 14:04 UTC
**Describe the bug**
Three tests fails. 
1. test_user_can_get_citizen1_guardians in test_user_controller.py"
2.  in test_pictogram_can_update_new_pictogram_image in test_pictogram_controller.py"
3.  in test_pictogram_can_get_public_pictogram_image in test_pictogram_controller.py"
 
**To Reproduce**
1. Go to path Giraf/web-api/GirafIntegrationTest/
2. Run test.py

**Expected behavior**
all 217 tests passed

**Actual behavior**
3/217 tests failed

**Comment by joandrsn** [comment] 2020-04-29 14:29
Is this not the same as #109 ?

**Comment by dkalaxdk** [comment] 2020-12-11 07:36
Duplicate of #109

**Closed** 2020-12-11 07:36 UTC
Labels: duplicate, priority: high, type: bug
